# Generated by Django 3.2.16 on 2024-05-16 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_managers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('created_at', '-pub_date'), 'verbose_name': 'публикация', 'verbose_name_plural': 'Публикации'},
        ),
    ]
