# Generated by Django 3.2.16 on 2024-05-16 12:27

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='category',
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
    ]
