# Generated by Django 3.2.16 on 2024-05-30 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_post_image'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='post',
            managers=[
            ],
        ),
    ]
